apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seerrplay
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/oploy-fr/seerrplay-website
    newTag: sha-049ab3feb20c83fb61ef89f29b35003f4570d04c
