apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seerrplay
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/oploy-fr/seerrplay-website
    newTag: sha-e058bc92ac7d158a7b2aa9db6dae10919133e16b
