apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seerrplay
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/oploy-fr/seerrplay-website
    newTag: sha-ae2c684ac61e5d7b0d38868078e131c61c374f2f
